services:
  caddy:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/stoat-caddy-waf:latest
    container_name: caddy-waf
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      CADDY_EMAIL: ${CADDY_EMAIL}
      TURN_REALM: ${TURN_REALM}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

  coturn:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/stoat-coturn:4.9.0-trixie
    container_name: coturn-relay
    restart: always
    depends_on:
      - caddy
    network_mode: host
    environment:
      EXTERNAL_IP: ${STATIC_IP}
      TURN_REALM: ${TURN_REALM}
      TURN_SHARED_SECRET: ${TURN_SHARED_SECRET}
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf:ro
      - caddy_data:/caddy-certs:ro

volumes:
  caddy_data:
  caddy_config:
